"""agent 领域模型：Agent/Session/Task 聚合 + 内核步状态机与扩展点值对象（docs/Agent/02）。"""

from services.agent.domain.model.agent import ALLOWED_AGENT_TOOLS, Agent, AgentAdapterInfo, AgentError, AgentStatus
from services.agent.domain.model.kernel_actions import (
    ActionDecision,
    ApprovalTicket,
    CodeAction,
    ExecutionMode,
    ExecutionResult,
    SandboxLease,
    SandboxSpec,
    StepResult,
    ToolCall,
    ToolResult,
)
from services.agent.domain.model.kernel_context import (
    ContextBlock,
    ExtensionMeta,
    KernelEvent,
    SinkAck,
    StepRef,
    TaskRef,
    TenantContext,
    TrustLevel,
)
from services.agent.domain.model.kernel_gates import (
    GateFinding,
    GateReport,
    GateVerdict,
    RunOutcome,
    ValidationReport,
)
from services.agent.domain.model.kernel_planning import (
    ConsolidationDecision,
    CriterionReport,
    MemoryCandidate,
    PlanCandidate,
    PlanMode,
    PlanStep,
    ReasoningRequest,
    ReasoningResult,
    RecallItem,
    SuccessCriterion,
)
from services.agent.domain.model.session import Session
from services.agent.domain.model.step_state import (
    BudgetWatermark,
    LoopStage,
    StepState,
    StepStateError,
    StepStatus,
)
from services.agent.domain.model.task import Run, RunStatus, Task, TaskError, TaskEvent, TaskStatus

__all__ = [
    "ALLOWED_AGENT_TOOLS",
    "ActionDecision",
    "Agent",
    "AgentAdapterInfo",
    "AgentError",
    "AgentStatus",
    "ApprovalTicket",
    "BudgetWatermark",
    "CodeAction",
    "ConsolidationDecision",
    "ContextBlock",
    "CriterionReport",
    "ExecutionMode",
    "ExecutionResult",
    "ExtensionMeta",
    "GateFinding",
    "GateReport",
    "GateVerdict",
    "KernelEvent",
    "LoopStage",
    "MemoryCandidate",
    "PlanCandidate",
    "PlanMode",
    "PlanStep",
    "ReasoningRequest",
    "ReasoningResult",
    "RecallItem",
    "Run",
    "RunOutcome",
    "RunStatus",
    "SandboxLease",
    "SandboxSpec",
    "Session",
    "SinkAck",
    "StepRef",
    "StepResult",
    "StepState",
    "StepStateError",
    "StepStatus",
    "SuccessCriterion",
    "Task",
    "TaskError",
    "TaskEvent",
    "TaskRef",
    "TaskStatus",
    "TenantContext",
    "ToolCall",
    "ToolResult",
    "TrustLevel",
    "ValidationReport",
]
