"""m1_m2 first 27 tables

Revision ID: 367b405f344b
Revises:
Create Date: 2026-09-26 19:44:37.150405

Discipline (arch 06 / database/01): additive-only; single head; data seeds in data migrations.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "367b405f344b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_adapters",
        sa.Column("agent_tool", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("runtime_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("health_endpoint", sa.String(length=256), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_adapters")),
        sa.UniqueConstraint("agent_tool", "version", name="uk_agent_adapters_agent_tool_version"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("params_digest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user','api_key','agent','system')", name=op.f("ck_audit_logs_ck_audit_logs_actor_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_trace_id"), "audit_logs", ["trace_id"], unique=False)
    op.create_index("ix_audit_tenant_time", "audit_logs", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uk_roles_code")),
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("plan IN ('free','pro','ent')", name=op.f("ck_tenants_ck_tenants_plan")),
        sa.CheckConstraint("status IN ('active','suspended')", name=op.f("ck_tenants_ck_tenants_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uk_tenants_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "email", name="uk_users_tenant_id_email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("agent_tool", sa.String(length=32), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("adapter_id", sa.UUID(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('enabled','disabled')", name=op.f("ck_agents_ck_agents_status")),
        sa.ForeignKeyConstraint(
            ["adapter_id"], ["agent_adapters.id"], name=op.f("fk_agents_adapter_id_agent_adapters")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("tenant_id", "name", name="uk_agents_tenant_id_name"),
    )
    op.create_index(op.f("ix_agents_agent_tool"), "agents", ["agent_tool"], unique=False)
    op.create_index(op.f("ix_agents_tenant_id"), "agents", ["tenant_id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], name=op.f("fk_api_keys_owner_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_prefix", name=op.f("uk_api_keys_key_prefix")),
    )
    op.create_index(op.f("ix_api_keys_owner_user_id"), "api_keys", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_api_keys_tenant_id"), "api_keys", ["tenant_id"], unique=False)
    op.create_table(
        "evaluation_runs",
        sa.Column("benchmark_type", sa.String(length=32), nullable=False),
        sa.Column("benchmark_version", sa.String(length=32), nullable=False),
        sa.Column("trigger_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("baseline_run_id", sa.UUID(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("delta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("passed", sa.BOOLEAN(), nullable=False),
        sa.Column("started_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "benchmark_type IN ('retrieval_qa','agent_task','extraction_precision')",
            name=op.f("ck_evaluation_runs_benchmark_type"),
        ),
        sa.ForeignKeyConstraint(
            ["baseline_run_id"], ["evaluation_runs.id"], name=op.f("fk_evaluation_runs_baseline_run_id_evaluation_runs")
        ),
        sa.ForeignKeyConstraint(["started_by"], ["users.id"], name=op.f("fk_evaluation_runs_started_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_index("idx_eval_runs", "evaluation_runs", ["tenant_id", "benchmark_type", "created_at"], unique=False)
    op.create_index(op.f("ix_evaluation_runs_tenant_id"), "evaluation_runs", ["tenant_id"], unique=False)
    op.create_table(
        "ontologies",
        sa.Column("iri_base", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scheme_tier", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("owner_business", sa.UUID(), nullable=True),
        sa.Column("owner_engineer", sa.UUID(), nullable=True),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scheme_tier IN ('glossary','light_graph','heavy')", name=op.f("ck_ontologies_ck_ontologies_scheme_tier")
        ),
        sa.CheckConstraint(
            "status IN ('draft','published','deprecated')", name=op.f("ck_ontologies_ck_ontologies_status")
        ),
        sa.ForeignKeyConstraint(["owner_business"], ["users.id"], name=op.f("fk_ontologies_owner_business_users")),
        sa.ForeignKeyConstraint(["owner_engineer"], ["users.id"], name=op.f("fk_ontologies_owner_engineer_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontologies")),
        sa.UniqueConstraint("tenant_id", "iri_base", name="uk_ontologies_tenant_id_iri_base"),
    )
    op.create_index(op.f("ix_ontologies_tenant_id"), "ontologies", ["tenant_id"], unique=False)
    op.create_table(
        "review_tickets",
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitter_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("sla_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','pending_review','approved','rejected','published','cancelled')",
            name=op.f("ck_review_tickets_status"),
        ),
        sa.CheckConstraint(
            "target_type IN ('ontology_candidate','knowledge_instance','memory_l2_upgrade','plugin_listing','writeback_incident')",
            name=op.f("ck_review_tickets_target_type"),
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], name=op.f("fk_review_tickets_reviewer_id_users")),
        sa.ForeignKeyConstraint(["submitter_id"], ["users.id"], name=op.f("fk_review_tickets_submitter_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_tickets")),
    )
    op.create_index("idx_review_queue", "review_tickets", ["tenant_id", "status", "created_at"], unique=False)
    op.create_index(op.f("ix_review_tickets_tenant_id"), "review_tickets", ["tenant_id"], unique=False)
    op.create_index(
        "uk_review_one_open",
        "review_tickets",
        ["tenant_id", "target_type", "target_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('draft','pending_review')"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role_id", name="uk_user_roles_user_id_role_id"),
    )
    op.create_index(op.f("ix_user_roles_tenant_id"), "user_roles", ["tenant_id"], unique=False)
    op.create_table(
        "evaluation_results",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "verdict IN ('pass','fail','skip')", name=op.f("ck_evaluation_results_ck_evaluation_results_verdict")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["evaluation_runs.id"], name=op.f("fk_evaluation_results_run_id_evaluation_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_results")),
        sa.UniqueConstraint("run_id", "case_id", name="uk_evaluation_results_run_id_case_id"),
    )
    op.create_index(op.f("ix_evaluation_results_tenant_id"), "evaluation_results", ["tenant_id"], unique=False)
    op.create_table(
        "kb_collections",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ontology_id", sa.UUID(), nullable=True),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.Column("chunk_defaults", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','archived')", name=op.f("ck_kb_collections_ck_kb_collections_status")),
        sa.ForeignKeyConstraint(
            ["ontology_id"], ["ontologies.id"], name=op.f("fk_kb_collections_ontology_id_ontologies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_collections")),
        sa.UniqueConstraint("tenant_id", "name", name="uk_kb_collections_tenant_id_name"),
    )
    op.create_index(op.f("ix_kb_collections_tenant_id"), "kb_collections", ["tenant_id"], unique=False)
    op.create_table(
        "ontology_versions",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("ontology_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("artifact_key", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.CHAR(length=64), nullable=False),
        sa.Column("triple_count", sa.Integer(), nullable=True),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ontology_id"], ["ontologies.id"], name=op.f("fk_ontology_versions_ontology_id_ontologies")
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_ontology_versions_parent_version_id_ontology_versions"),
        ),
        sa.ForeignKeyConstraint(["published_by"], ["users.id"], name=op.f("fk_ontology_versions_published_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_versions")),
        sa.UniqueConstraint("ontology_id", "version", name="uk_ontology_versions_ontology_id_version"),
        sa.UniqueConstraint("ontology_id", "version_no", name="uk_ontology_versions_ontology_id_version_no"),
    )
    op.create_index(op.f("ix_ontology_versions_ontology_id"), "ontology_versions", ["ontology_id"], unique=False)
    op.create_index(op.f("ix_ontology_versions_tenant_id"), "ontology_versions", ["tenant_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("channel IN ('web','api','cli')", name=op.f("ck_sessions_ck_sessions_channel")),
        sa.CheckConstraint(
            "status IN ('created','active','idle','closed','archived')", name=op.f("ck_sessions_ck_sessions_status")
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_sessions_agent_id_agents")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_tenant_id"), "sessions", ["tenant_id"], unique=False)
    op.create_index(
        "ix_sessions_tenant_user_recent", "sessions", ["tenant_id", "user_id", "last_message_at"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("kb_collection_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("minio_key", sa.String(length=512), nullable=False),
        sa.Column("checksum_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source_type IN ('upload','api')", name=op.f("ck_documents_ck_documents_source_type")),
        sa.CheckConstraint(
            "status IN ('uploaded','preprocessed','extracting','aligning','validating','pending_review','indexed','failed')",
            name=op.f("ck_documents_status"),
        ),
        sa.ForeignKeyConstraint(
            ["kb_collection_id"], ["kb_collections.id"], name=op.f("fk_documents_kb_collection_id_kb_collections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "tenant_id",
            "kb_collection_id",
            "checksum_sha256",
            name="uk_documents_tenant_id_kb_collection_id_checksum_sha256",
        ),
    )
    op.create_index(
        "ix_documents_current",
        "documents",
        ["tenant_id", "kb_collection_id"],
        unique=False,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_index("ix_documents_status", "documents", ["status"], unique=False)
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("ag_ui_events", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("token_in", sa.Integer(), nullable=True),
        sa.Column("token_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("role IN ('user','assistant','tool','system')", name=op.f("ck_messages_ck_messages_role")),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], name=op.f("fk_messages_session_id_sessions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("session_id", "seq", name="uk_messages_session_id_seq"),
    )
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)
    op.create_table(
        "ontology_changesets",
        sa.Column("ontology_id", sa.UUID(), nullable=False),
        sa.Column("from_version_id", sa.UUID(), nullable=True),
        sa.Column("to_version_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("impact_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("applicant_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_business", sa.UUID(), nullable=True),
        sa.Column("reviewer_engineer", sa.UUID(), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','in_review','published','rejected','rolled_back')",
            name=op.f("ck_ontology_changesets_ck_ontology_changesets_status"),
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["users.id"], name=op.f("fk_ontology_changesets_applicant_id_users")),
        sa.ForeignKeyConstraint(
            ["from_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_ontology_changesets_from_version_id_ontology_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["ontology_id"], ["ontologies.id"], name=op.f("fk_ontology_changesets_ontology_id_ontologies")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_business"], ["users.id"], name=op.f("fk_ontology_changesets_reviewer_business_users")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_engineer"], ["users.id"], name=op.f("fk_ontology_changesets_reviewer_engineer_users")
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], name=op.f("fk_ontology_changesets_reviewer_id_users")),
        sa.ForeignKeyConstraint(
            ["to_version_id"],
            ["ontology_versions.id"],
            name=op.f("fk_ontology_changesets_to_version_id_ontology_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_changesets")),
    )
    op.create_index("ix_changesets_ontology_status", "ontology_changesets", ["ontology_id", "status"], unique=False)
    op.create_index(op.f("ix_ontology_changesets_tenant_id"), "ontology_changesets", ["tenant_id"], unique=False)
    op.create_index(
        "uk_changesets_one_active",
        "ontology_changesets",
        ["tenant_id", "ontology_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('draft','in_review')"),
    )
    op.create_table(
        "tasks",
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("active_run_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','succeeded','failed','cancelled')", name=op.f("ck_tasks_ck_tasks_status")
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_tasks_agent_id_agents")),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], name=op.f("fk_tasks_session_id_sessions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_tasks_tenant_id_idempotency_key"),
    )
    op.create_index("ix_tasks_queue", "tasks", ["status", "priority", "created_at"], unique=False)
    op.create_index(op.f("ix_tasks_tenant_id"), "tasks", ["tenant_id"], unique=False)
    op.create_index(
        "uk_tasks_one_active_run",
        "tasks",
        ["tenant_id", "session_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "axioms",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("subject_iri", sa.String(length=256), nullable=False),
        sa.Column("object_iri", sa.String(length=256), nullable=True),
        sa.Column("expression", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("review_state", sa.String(length=16), nullable=True),
        sa.Column("ontology_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("changeset_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("source IN ('manual','llm_candidate')", name=op.f("ck_axioms_ck_axioms_source")),
        sa.ForeignKeyConstraint(
            ["changeset_id"], ["ontology_changesets.id"], name=op.f("fk_axioms_changeset_id_ontology_changesets")
        ),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], name=op.f("fk_axioms_ontology_id_ontologies")),
        sa.ForeignKeyConstraint(
            ["version_id"], ["ontology_versions.id"], name=op.f("fk_axioms_version_id_ontology_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_axioms")),
    )
    op.create_index(op.f("ix_axioms_tenant_id"), "axioms", ["tenant_id"], unique=False)
    op.create_index("ix_axioms_version_kind", "axioms", ["version_id", "kind"], unique=False)
    op.create_table(
        "classes",
        sa.Column("iri", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=True),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("subclass_of", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("equivalent_class", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_behavior", sa.BOOLEAN(), nullable=False),
        sa.Column("state_attribute", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ontology_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("changeset_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changeset_id"], ["ontology_changesets.id"], name=op.f("fk_classes_changeset_id_ontology_changesets")
        ),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], name=op.f("fk_classes_ontology_id_ontologies")),
        sa.ForeignKeyConstraint(
            ["version_id"], ["ontology_versions.id"], name=op.f("fk_classes_version_id_ontology_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("version_id", "iri", name="uk_classes_version_id_iri"),
    )
    op.create_index(op.f("ix_classes_tenant_id"), "classes", ["tenant_id"], unique=False)
    op.create_index("ix_classes_tenant_ontology", "classes", ["tenant_id", "ontology_id"], unique=False)
    op.create_table(
        "document_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_document_chunks_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "seq", name="uk_document_chunks_document_id_seq"),
    )
    op.create_index(op.f("ix_document_chunks_tenant_id"), "document_chunks", ["tenant_id"], unique=False)
    op.create_table(
        "kb_pipeline_step",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("step", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("checkpoint_uri", sa.String(length=512), nullable=True),
        sa.Column("attempt", sa.SmallInteger(), nullable=False),
        sa.Column("worker_lease", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','done','failed')",
            name=op.f("ck_kb_pipeline_step_ck_kb_pipeline_step_status"),
        ),
        sa.CheckConstraint(
            "step IN ('preprocess','env_setup','extract','align','validate','archive','review')",
            name=op.f("ck_kb_pipeline_step_step"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_kb_pipeline_step_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_pipeline_step")),
    )
    op.create_index(op.f("ix_kb_pipeline_step_tenant_id"), "kb_pipeline_step", ["tenant_id"], unique=False)
    op.create_table(
        "properties",
        sa.Column("iri", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=True),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("domain_iri", sa.String(length=256), nullable=True),
        sa.Column("range_iri", sa.String(length=256), nullable=True),
        sa.Column("type_of_terms", sa.String(length=64), nullable=True),
        sa.Column("functional", sa.BOOLEAN(), nullable=False),
        sa.Column("constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ontology_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("changeset_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("kind IN ('datatype','object')", name=op.f("ck_properties_ck_properties_kind")),
        sa.ForeignKeyConstraint(
            ["changeset_id"], ["ontology_changesets.id"], name=op.f("fk_properties_changeset_id_ontology_changesets")
        ),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], name=op.f("fk_properties_ontology_id_ontologies")),
        sa.ForeignKeyConstraint(
            ["version_id"], ["ontology_versions.id"], name=op.f("fk_properties_version_id_ontology_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
        sa.UniqueConstraint("version_id", "iri", name="uk_properties_version_id_iri"),
    )
    op.create_index(op.f("ix_properties_tenant_id"), "properties", ["tenant_id"], unique=False)
    op.create_table(
        "rules",
        sa.Column("route", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("event_class_iri", sa.String(length=256), nullable=True),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("action_ref", sa.String(length=256), nullable=True),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("review_state", sa.String(length=16), nullable=True),
        sa.Column("ontology_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("changeset_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("route IN ('owl_axiom','shacl','engine')", name=op.f("ck_rules_ck_rules_route")),
        sa.CheckConstraint("severity IN ('error','warn')", name=op.f("ck_rules_ck_rules_severity")),
        sa.ForeignKeyConstraint(
            ["changeset_id"], ["ontology_changesets.id"], name=op.f("fk_rules_changeset_id_ontology_changesets")
        ),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], name=op.f("fk_rules_ontology_id_ontologies")),
        sa.ForeignKeyConstraint(
            ["version_id"], ["ontology_versions.id"], name=op.f("fk_rules_version_id_ontology_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
        sa.UniqueConstraint("version_id", "name", name="uk_rules_version_id_name"),
    )
    op.create_index(op.f("ix_rules_tenant_id"), "rules", ["tenant_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("seq_start", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','waiting_tool','completed','failed','timeout','cancelled')",
            name=op.f("ck_runs_status"),
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_runs_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_task_id"), "runs", ["task_id"], unique=False)
    op.create_index(op.f("ix_runs_tenant_id"), "runs", ["tenant_id"], unique=False)
    op.create_index(
        "uk_runs_one_active",
        "runs",
        ["tenant_id", "task_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued','running','waiting_tool')"),
    )
    op.create_table(
        "task_events",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_task_events_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_events")),
        sa.UniqueConstraint("task_id", "seq", name="uk_task_events_task_id_seq"),
    )
    op.create_index(op.f("ix_task_events_tenant_id"), "task_events", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_events_tenant_id"), table_name="task_events")
    op.drop_table("task_events")
    op.drop_index(
        "uk_runs_one_active",
        table_name="runs",
        postgresql_where=sa.text("status IN ('queued','running','waiting_tool')"),
    )
    op.drop_index(op.f("ix_runs_tenant_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_task_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_rules_tenant_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_properties_tenant_id"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_kb_pipeline_step_tenant_id"), table_name="kb_pipeline_step")
    op.drop_table("kb_pipeline_step")
    op.drop_index(op.f("ix_document_chunks_tenant_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_classes_tenant_ontology", table_name="classes")
    op.drop_index(op.f("ix_classes_tenant_id"), table_name="classes")
    op.drop_table("classes")
    op.drop_index("ix_axioms_version_kind", table_name="axioms")
    op.drop_index(op.f("ix_axioms_tenant_id"), table_name="axioms")
    op.drop_table("axioms")
    op.drop_index("uk_tasks_one_active_run", table_name="tasks", postgresql_where=sa.text("status = 'running'"))
    op.drop_index(op.f("ix_tasks_tenant_id"), table_name="tasks")
    op.drop_index("ix_tasks_queue", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(
        "uk_changesets_one_active",
        table_name="ontology_changesets",
        postgresql_where=sa.text("status IN ('draft','in_review')"),
    )
    op.drop_index(op.f("ix_ontology_changesets_tenant_id"), table_name="ontology_changesets")
    op.drop_index("ix_changesets_ontology_status", table_name="ontology_changesets")
    op.drop_table("ontology_changesets")
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index("ix_documents_status", table_name="documents")
    op.drop_index("ix_documents_current", table_name="documents", postgresql_where=sa.text("valid_to IS NULL"))
    op.drop_table("documents")
    op.drop_index("ix_sessions_tenant_user_recent", table_name="sessions")
    op.drop_index(op.f("ix_sessions_tenant_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_ontology_versions_tenant_id"), table_name="ontology_versions")
    op.drop_index(op.f("ix_ontology_versions_ontology_id"), table_name="ontology_versions")
    op.drop_table("ontology_versions")
    op.drop_index(op.f("ix_kb_collections_tenant_id"), table_name="kb_collections")
    op.drop_table("kb_collections")
    op.drop_index(op.f("ix_evaluation_results_tenant_id"), table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_user_roles_tenant_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(
        "uk_review_one_open",
        table_name="review_tickets",
        postgresql_where=sa.text("status IN ('draft','pending_review')"),
    )
    op.drop_index(op.f("ix_review_tickets_tenant_id"), table_name="review_tickets")
    op.drop_index("idx_review_queue", table_name="review_tickets")
    op.drop_table("review_tickets")
    op.drop_index(op.f("ix_ontologies_tenant_id"), table_name="ontologies")
    op.drop_table("ontologies")
    op.drop_index(op.f("ix_evaluation_runs_tenant_id"), table_name="evaluation_runs")
    op.drop_index("idx_eval_runs", table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_api_keys_tenant_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_owner_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_agents_tenant_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_agent_tool"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")
    op.drop_table("roles")
    op.drop_index("ix_audit_tenant_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_trace_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("agent_adapters")
    # ### end Alembic commands ###
