"""server_default alignment with database/01 contract

Revision ID: 5af72ad1d6c7
Revises: c8d5e2f7a931
Create Date: 2026-09-27 01:46:19.823773

Discipline (arch 06 / database/01): additive-only; single head; data seeds in data migrations.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "5af72ad1d6c7"
down_revision: Union[str, None] = "c8d5e2f7a931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "egress_policies", "version", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "egress_policies",
        "rules",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "egress_policies", "enabled", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    op.alter_column("egress_policies", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column(
        "egress_policies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "egress_policies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(op.f("ix_egress_policies_tenant_id"), "egress_policies", ["tenant_id"], unique=False)
    op.alter_column(
        "sandbox_events",
        "detail",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column("sandbox_events", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.create_index("idx_sbx_events_inst", "sandbox_events", ["tenant_id", "instance_id", "created_at"], unique=False)
    op.create_index(op.f("ix_sandbox_events_tenant_id"), "sandbox_events", ["tenant_id"], unique=False)
    op.alter_column(
        "sandbox_instances", "status", existing_type=sa.VARCHAR(length=16), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "sandbox_instances",
        "backend",
        existing_type=sa.VARCHAR(length=16),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column("sandbox_instances", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column(
        "sandbox_instances",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_instances",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index("idx_sbx_inst_owner", "sandbox_instances", ["tenant_id", "owner_kind", "owner_ref"], unique=False)
    op.create_index(
        "idx_sbx_inst_status",
        "sandbox_instances",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status NOT IN ('terminated')"),
    )
    op.create_index(op.f("ix_sandbox_instances_tenant_id"), "sandbox_instances", ["tenant_id"], unique=False)
    op.alter_column(
        "sandbox_profiles",
        "cpu_limit",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles", "mem_limit_mb", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "sandbox_profiles", "pids_limit", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "sandbox_profiles", "output_quota_kb", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "sandbox_profiles",
        "base_image",
        existing_type=sa.VARCHAR(length=256),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "toolkit_ref",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles", "qos", existing_type=sa.VARCHAR(length=2), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "sandbox_profiles", "is_builtin", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    op.alter_column("sandbox_profiles", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column(
        "sandbox_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_snapshots", "source", existing_type=sa.VARCHAR(length=16), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "sandbox_snapshots", "sanitized", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "sandbox_snapshots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column("sandbox_snapshots", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.create_index(op.f("ix_sandbox_snapshots_tenant_id"), "sandbox_snapshots", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sandbox_snapshots_tenant_id"), table_name="sandbox_snapshots")
    op.alter_column(
        "sandbox_snapshots",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_snapshots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_snapshots",
        "sanitized",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_snapshots",
        "source",
        existing_type=sa.VARCHAR(length=16),
        server_default=sa.text("'hibernate'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "is_builtin",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "qos",
        existing_type=sa.VARCHAR(length=2),
        server_default=sa.text("'ls'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "toolkit_ref",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "base_image",
        existing_type=sa.VARCHAR(length=256),
        server_default=sa.text("'docker.m.daocloud.io/library/python:3.12-slim'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "output_quota_kb",
        existing_type=sa.INTEGER(),
        server_default=sa.text("10240"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "pids_limit",
        existing_type=sa.INTEGER(),
        server_default=sa.text("256"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "mem_limit_mb",
        existing_type=sa.INTEGER(),
        server_default=sa.text("512"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_profiles",
        "cpu_limit",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        server_default=sa.text("0.5"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_sandbox_instances_tenant_id"), table_name="sandbox_instances")
    op.drop_index(
        "idx_sbx_inst_status", table_name="sandbox_instances", postgresql_where=sa.text("status NOT IN ('terminated')")
    )
    op.drop_index("idx_sbx_inst_owner", table_name="sandbox_instances")
    op.alter_column(
        "sandbox_instances",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_instances",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_instances",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_instances",
        "backend",
        existing_type=sa.VARCHAR(length=16),
        server_default=sa.text("'docker'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_instances",
        "status",
        existing_type=sa.VARCHAR(length=16),
        server_default=sa.text("'creating'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_sandbox_events_tenant_id"), table_name="sandbox_events")
    op.drop_index("idx_sbx_events_inst", table_name="sandbox_events")
    op.alter_column(
        "sandbox_events",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sandbox_events",
        "detail",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_egress_policies_tenant_id"), table_name="egress_policies")
    op.alter_column(
        "egress_policies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "egress_policies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "egress_policies",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "egress_policies",
        "enabled",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "egress_policies",
        "rules",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "egress_policies", "version", existing_type=sa.INTEGER(), server_default=sa.text("1"), existing_nullable=False
    )
    # ### end Alembic commands ###
