"""audit fixes uk users check indexes

Revision ID: ff0a49ea346d
Revises: 367b405f344b
Create Date: 2026-09-27 00:02:46.860191

Discipline (arch 06 / database/01): additive-only; single head; data seeds in data migrations.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ff0a49ea346d"
down_revision: Union[str, None] = "367b405f344b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_api_keys_tenant_owner", "api_keys", ["tenant_id", "owner_user_id"], unique=False)
    op.create_index("ix_audit_resource", "audit_logs", ["resource_type", "resource_id"], unique=False)
    op.create_unique_constraint("uk_kb_pipeline_step_doc_step", "kb_pipeline_step", ["document_id", "step"])
    op.create_index("ix_messages_session_created", "messages", ["session_id", "created_at"], unique=False)
    op.create_index("ix_runs_task_created", "runs", ["task_id", "created_at"], unique=False)
    op.drop_index(op.f("ix_sessions_tenant_user_recent"), table_name="sessions")
    op.create_index(
        "ix_sessions_tenant_user_recent",
        "sessions",
        ["tenant_id", "user_id", sa.literal_column("last_message_at DESC")],
        unique=False,
    )
    op.create_index("ix_tasks_tenant_session", "tasks", ["tenant_id", "session_id"], unique=False)
    # ### end Alembic commands ###
    # 2026-09-26 缺口核查修复：users.status CHECK（autogenerate 不检测 CHECK 增量，手工补登；
    # 传 ORM 声明名，运行时由 metadata 约定 ck_%(table_name)s_%(constraint_name)s 展开为最终名）
    op.create_check_constraint("ck_users_status", "users", "status IN ('active','disabled')")


def downgrade() -> None:
    # 2026-09-26 缺口核查修复：users.status CHECK 回滚（传 ORM 声明名，运行时约定展开）
    op.drop_constraint("ck_users_status", "users", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_tenant_session", table_name="tasks")
    op.drop_index("ix_sessions_tenant_user_recent", table_name="sessions")
    op.create_index(
        op.f("ix_sessions_tenant_user_recent"), "sessions", ["tenant_id", "user_id", "last_message_at"], unique=False
    )
    op.drop_index("ix_runs_task_created", table_name="runs")
    op.drop_index("ix_messages_session_created", table_name="messages")
    op.drop_constraint("uk_kb_pipeline_step_doc_step", "kb_pipeline_step", type_="unique")
    op.drop_index("ix_audit_resource", table_name="audit_logs")
    op.drop_index("ix_api_keys_tenant_owner", table_name="api_keys")
    # ### end Alembic commands ###
